apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    implementation: "microprofile"
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      app: "{{ .Release.Name }}-{{  .Chart.Name }}-selector"
      release: {{ .Release.Name }}
      implementation: "microprofile"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{  .Chart.Name }}-selector"
        release: {{ .Release.Name }}
        implementation: "microprofile"
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
        - containerPort: {{ .Values.service.port }}
          name: zipkin-api
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
          initialDelaySeconds: 30
          timeoutSeconds: 60
