{{- if not (eq .Release.Namespace "default") }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "bluecompute.fullname" . }}-cluster-role-binding
  labels:
    {{- include "bluecompute.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "bluecompute.fullname" . }}-cluster-role
{{- end }}