apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.hs256key.secretName }}
  labels:
    {{- include "bluecompute.labels" . | indent 4 }}
data:
  key: {{ (.Values.global.hs256key.secret | default (randAlphaNum 256)) | b64enc }}
type: Opaque