{{- if .Values.createImagePolicy }}
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ClusterImagePolicy
metadata:
  name: ibmcase
  labels:
    {{- include "bluecompute.labels" . | indent 4 }}
spec:
  repositories:
  - name: docker.io/*
    policy:
      va:
        enabled: false
  - name: docker.elastic.co/*
    policy:
      va:
        enabled: false
{{- end }}