{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  #annotations:
  #  ingress.kubernetes.io/rewrite-target: /
  labels:
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name}}-{{ .Chart.Version }}
spec:
  {{- if .Values.tls.enabled }}
  tls:
  {{- if .Values.web.enabled }}
  {{- if .Values.ingress.hostnames.app}}
  - hosts:
    - {{ .Values.ingress.hostnames.app }}
    secretName: "{{ template "tlsSecretName" . }}"
  {{- end }}
  {{- end }}
  {{- if .Values.ingress.hostnames.api }}
  - hosts:
    - {{ .Values.ingress.hostnames.api }}
    secretName: "{{ template "tlsSecretName" . }}"
  {{- end }}
  {{- end }}
  rules:
  {{- if .Values.web.enabled }}
  {{- if .Values.ingress.hostnames.app}}
  - host: {{ .Values.ingress.hostnames.app }}
    http:
      paths:
      - path: {{ .Values.web.ingress.path }}
        backend:
          serviceName: "{{- .Release.Name }}-{{ .Values.web.service.name }}"
          servicePort: {{ .Values.web.service.externalPort }}
  {{- end }}
  {{- end }}
  {{- if .Values.ingress.hostnames.api }}
  - host: {{ .Values.ingress.hostnames.api }}
    http:
      paths:
      {{- if .Values.auth.enabled }}
      - path: {{ .Values.auth.ingress.path }}
        backend:
          serviceName: "{{- .Release.Name }}-{{ .Values.auth.service.name }}"
          servicePort: {{ .Values.auth.service.externalPort }}
      {{- end }}
      {{- if .Values.catalog.enabled }}
      - path: {{ .Values.catalog.ingress.path }}
        backend:
          serviceName: "{{- .Release.Name }}-{{ .Values.catalog.service.name }}"
          servicePort: {{ .Values.catalog.service.externalPort }}
      {{- end }}
      {{- if .Values.customer.enabled }}
      - path: {{ .Values.customer.ingress.path }}
        backend:
          serviceName: "{{- .Release.Name }}-{{ .Values.customer.service.name }}"
          servicePort: {{ .Values.customer.service.externalPort }}
      {{- end }}
      {{- if .Values.inventory.enabled }}
      - path: {{ .Values.inventory.ingress.path }}
        backend:
          serviceName: "{{- .Release.Name }}-{{ .Values.inventory.service.name }}"
          servicePort: {{ .Values.inventory.service.externalPort }}
      {{- end }}
      {{- if .Values.orders.enabled }}
      - path: {{ .Values.orders.ingress.path }}
        backend:
          serviceName: "{{- .Release.Name }}-{{ .Values.orders.service.name }}"
          servicePort: {{ .Values.orders.service.externalPort }}
      {{- end }}
  {{- end }}
{{- end }}