{{- if not (eq .Release.Namespace "default") }}
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "bluecompute.fullname" . }}-pod-security-policy
  labels:
    {{- include "bluecompute.labels" . | indent 4 }}
spec:
  allowedCapabilities:
  - IPC_LOCK
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - max: 65535
    min: 1
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
{{- end }}