{{- if .Values.tls.secretName }}
{{- else if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-tls
  labels:
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name}}-{{ .Chart.Version }}
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
type: Opaque
{{- end }}