# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}-alertmanager
    chart: {{ .Chart.Name }}
    component: alertmanager
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-alertmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "prometheus.fullname" . }}-alertmanager
        chart: {{ .Chart.Name }}
        component: alertmanager
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        productName: alertmanager
        productVersion: 0.13.0
        productID: none
    spec:
    {{- if eq .Values.mode "managed" }}
      tolerations:
      - key: "dedicated"
        operator: "Exists"
        effect: "NoSchedule"
    {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
            {{- if eq .Values.mode "managed" }}
              - key: management
                operator: In
                values:
                - "true"
            {{- end }}
      containers:
        - name: configmap-reload
          image: {{ .Values.configmapReload.image.repository }}:{{ .Values.configmapReload.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://localhost:9093/-/reload
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
        - name: alertmanager
          image: {{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/var/lib/alertmanager/data
          ports:
            - containerPort: 9093
          resources:
{{ toYaml .Values.alertmanager.resources | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: storage-volume
              mountPath: "/var/lib/alertmanager/data"
      {{- if or (eq .Values.mode "managed") .Values.tls.enabled }}
        - name: router
          image: {{ .Values.router.image.repository }}:{{ .Values.router.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["/opt/ibm/router/entry/entrypoint.sh"]
          ports:
          - name: router
            containerPort: 8080
          volumeMounts:
            - mountPath: "/opt/ibm/router/conf"
              name: router-config
            - mountPath: "/opt/ibm/router/certs"
              name: monitoring-certs
            - mountPath: "/opt/ibm/router/ca-certs"
              name: monitoring-ca-cert
            - mountPath: "/opt/ibm/router/entry"
              name: router-entry
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "prometheus.fullname" . }}-alertmanager
        - name: storage-volume
        {{- if .Values.alertmanager.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "prometheus.fullname" . }}-alertmanager
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if or (eq .Values.mode "managed") .Values.tls.enabled }}
        - name: router-config
          configMap:
            name: {{ template "prometheus.fullname" . }}-alertmanager-router-nginx-config
        - name: monitoring-certs
          secret:
            secretName: {{ template "monitoring.fullname" . }}-certs
        - name: monitoring-ca-cert
          secret:
            secretName: {{ template "monitoring.fullname" . }}-ca-cert
        - name: router-entry
          configMap:
            name: {{ template "monitoring.fullname" . }}-router-entry-config
            defaultMode: 0744
      {{- end }}
