# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "grafana.labels" . | indent 4 }}
  name: {{ template "grafana.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "grafana.labels" . | indent 6 }}
  template:
    metadata:
      labels: {{- include "grafana.labels" . | indent 8 }}
      annotations:
        productName: grafana
        productVersion: 4.6.3
        productID: none
    spec:
    {{- if eq .Values.mode "managed" }}
      tolerations:
      - key: "dedicated"
        operator: "Exists"
        effect: "NoSchedule"
    {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
            {{- if eq .Values.mode "managed" }}
              - key: management
                operator: In
                values:
                - "true"
            {{- end }}
      containers:
        - name: grafana
          image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["/opt/entry/entrypoint.sh"]
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "grafana.fullname" . }}-secret
                  key: username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "grafana.fullname" . }}-secret
                  key: password
          ports:
          - name: web
            containerPort: 3000
          resources:
{{ toYaml .Values.grafana.resources | indent 12 }}
          volumeMounts:
            - name: grafana-storage
              mountPath: "/var/lib/grafana"
            - name: config-volume
              mountPath: "/tmp/grafana/config"
            - name: dashboard-volume
              mountPath: "/tmp/grafana/dashboards"
            - mountPath: "/opt/entry"
              name: grafana-entry
      {{- if or (eq .Values.mode "managed") .Values.tls.enabled }}
        - name: router
          image: {{ .Values.router.image.repository }}:{{ .Values.router.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["/opt/ibm/router/entry/entrypoint.sh"]
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "grafana.fullname" . }}-secret
                  key: username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "grafana.fullname" . }}-secret
                  key: password
          ports:
          - name: router
            containerPort: 8080
          volumeMounts:
            - mountPath: "/opt/ibm/router/conf"
              name: router-config
            - mountPath: "/opt/ibm/router/certs"
              name: monitoring-certs
            - mountPath: "/opt/ibm/router/ca-certs"
              name: monitoring-ca-cert
            - mountPath: "/opt/ibm/router/entry"
              name: router-entry
      {{- end }}
      volumes:
        - name: grafana-storage
      {{- if .Values.grafana.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "grafana.fullname" . }}
      {{- else }}
          emptyDir: {}
      {{- end }}
        - name: config-volume
          configMap:
            name: {{ template "grafana.fullname" . }}
        - name: dashboard-volume
          configMap:
            name: {{ template "grafana.fullname" . }}-dashboards
        - name: grafana-entry
          configMap:
            name: {{ template "grafana.fullname" . }}-entry-config
            defaultMode: 0744
      {{- if or (eq .Values.mode "managed") .Values.tls.enabled }}
        - name: router-config
          configMap:
            name: {{ template "grafana.fullname" . }}-router-nginx-config
        - name: monitoring-certs
          secret:
            secretName: {{ template "monitoring.fullname" . }}-certs
        - name: monitoring-ca-cert
          secret:
            secretName: {{ template "monitoring.fullname" . }}-ca-cert
        - name: router-entry
          configMap:
            name: {{ template "monitoring.fullname" . }}-router-entry-config
            defaultMode: 0744
      {{- end }}
