apiVersion: v1
description: A Helm chart for Zipkin
name: zipkin
version: 0.0.1
home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
sources:
  - https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile/Zipkin
