---
# Source: bluecompute-ce/charts/web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: bluecompute
  labels:    
    app: "web"
    tier: "frontend"
    version: "v1"
    heritage: "Helm"
    release: "bluecompute"
    chart: web-0.6.0
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  selector:    
    app: "web"
    tier: "frontend"
    version: "v1"
    heritage: "Helm"
    release: "bluecompute"
    chart: web-0.6.0
