---
# Source: bluecompute-ce/charts/customer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: bluecompute
  labels:    
    app: "customer"
    tier: "backend"
    version: "v1"
    heritage: "Helm"
    release: "bluecompute"
    chart: customer-0.6.0
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8082
    targetPort: 8082
  selector:    
    app: "customer"
    tier: "backend"
    version: "v1"
    heritage: "Helm"
    release: "bluecompute"
    chart: customer-0.6.0
