# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

mode: standard
tls:
  enabled: false
imagePullPolicy: "IfNotPresent"

prometheus:
  image:
    repository: ibmcom/prometheus
    tag: v2.0.0
  port: 9090
  scrapeInterval: 1m
  evaluationInterval: 1m
  retention: 24h
  args: {}
  persistentVolume:
    enabled: false
    size: 10Gi
    storageClass: "-"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  alertRuleFiles: alertRules
  configFiles: prometheusConfig
  ## if true, will create rbac role and related rolebinding for k8s resource access
  ##
  rbacRoleCreation: true
  ingress:
    enabled: false
    annotations: {}
  service:
    type: NodePort
  etcdTarget:
    enabled: false
    etcdAddress: ["127.0.0.1"]
    etcdPort: "4001"
    secret: etcd-secret
    tlsConfig: {}

alertmanager:
  image:
    repository: ibmcom/alertmanager
    tag: v0.13.0
  port: 9093
  persistentVolume:
    enabled: false
    size: 1Gi
    storageClass: "-"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  configFiles: alermanagerConfig
  ingress:
    enabled: false
    annotations: {}
  service:
    type: NodePort

kubeStateMetrics:
  enabled: false
  image:
    repository: ibmcom/kube-state-metrics
    tag: v1.2.0
  port: 80

nodeExporter:
  enabled: false
  image:
    repository: ibmcom/node-exporter
    tag: v0.15.2
  port: 9100

grafana:
  image:
    repository: "ibmcom/grafana"
    tag: "4.6.3"
  port: 3000
  user: "admin"
  password: "admin"
  persistentVolume:
    enabled: false
    size: 1Gi
    storageClass: "-"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  configFiles: grafanaConfig
  ingress:
    enabled: false
    annotations: {}
  service:
    type: NodePort
  elasticsearchDash:
    enabled: false

collectdExporter:
  enabled: false
  image:
    repository: ibmcom/collectd-exporter
    tag: 0.3.1
  service:
    serviceMetricsPort: 9103
    serviceCollectorPort: 25826

configmapReload:
  image:
    repository: ibmcom/configmap-reload
    tag: v0.1

router:
  image:
    repository: ibmcom/icp-router
    tag: 2.2.0
  subjectAlt: 127.0.0.1

elasticsearchExporter:
  enabled: false
  image:
    repository: ibmcom/elasticsearch-exporter
    tag: 1.0.2
  esUri: http://elasticsearch:9200
  port: 9108

curl:
  image:
    repository: ibmcom/curl
    tag: 3.6

certGen:
  image:
    repository: ibmcom/icp-cert-gen
    tag: 1.0.0
