replicaCount: 1

image:
  repository: ibmcase/bluecompute-inventory
  pullPolicy: Always
  tag: latest

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

dataloader:
  image:
    repository: ibmcase/bluecompute-dataloader
    tag: latest

service:
  name: inventory
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

mysql:
  binding:
    name: binding-inventorydb-mysql

messagehub:
  enabled: false
  binding:
    name:
