dependencies:
  - name: auth
    version: 0.4.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: auth.enabled
  - name: catalog
    version: 0.4.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: catalog.enabled
  - name: catalogelasticsearch
    version: 0.3.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: catalogelasticsearch.enabled
  - name: customer
    version: 0.4.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: customer.enabled
  - name: customercouchdb
    version: 0.3.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: customercouchdb.enabled
  - name: inventory
    version: 0.4.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: inventory.enabled
  - name: inventorymysql
    version: 0.4.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: inventorymysql.enabled
  - name: orders
    version: 0.4.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: orders.enabled
  - name: ordersmysql
    version: 0.4.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: ordersmysql.enabled
  - name: web
    version: 0.4.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: web.enabled