dependencies:
  - name: auth
    version: 0.5.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts
    condition: auth.enabled
  - name: catalog
    version: 0.5.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts
    condition: catalog.enabled
  #- name: customer
  #  version: 0.5.0
  #  repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts
  #  condition: customer.enabled
  #- name: inventory
  #  version: 0.5.0
  #  repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts
  #  condition: inventory.enabled
  - name: orders
    version: 0.5.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts
    condition: orders.enabled
  - name: web
    version: 0.5.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts
    condition: web.enabled