---
# Source: bluecompute-ce/charts/mariadb/templates/tests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: openshift-orders-mariadb-tests
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h openshift-orders-mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }
