apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: bluecompute-cluster-role
  labels:
    app: bluecompute
rules: 
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - bluecompute-pod-security-policy
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: bluecompute-cluster-role-binding
  labels:
    app: bluecompute
subjects:
- kind: ServiceAccount
  name: default
  # Change this namespace to the you are installing the bluecompute-ce chart in
  namespace: bluecompute
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bluecompute-cluster-role
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: bluecompute-pod-security-policy
  # Change this namespace to the you are installing the bluecompute-ce chart in
  namespace: bluecompute
  labels:
    app: bluecompute
spec:
  allowedCapabilities:
  - IPC_LOCK
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - max: 65535
    min: 1
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'