---
# Source: bluecompute-ce/charts/catalog/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: bluecompute
  labels:    
    app: "catalog"
    tier: "backend"
    version: "v1"
    heritage: "Helm"
    release: "bluecompute"
    chart: catalog-0.6.0
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:    
    app: "catalog"
    tier: "backend"
    version: "v1"
    heritage: "Helm"
    release: "bluecompute"
    chart: catalog-0.6.0
