apiVersion: v1
kind: Secret
type: Opaque
data:
  api-key: {{ .Values.global.bluemix.apiKey | b64enc }}
metadata:
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ .Release.Name }}-bluemix-api-key
  namespace: {{ .Release.Namespace }}
