apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-audit-{{ randAlphaNum 5 | lower }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "99"
  labels:
    name: audit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-audit
      labels:
        name: audit
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: Never
      containers:
      - name: audit
        image: ibmcase/bluemix-cluster-deployer:latest
        command: [ "/bin/bash", "-c" ]
        args: 
        - >
            echo "Sending audit message to BlueCompute central";
            source /scripts/bx_login.sh;
            bx cs init;
            TIMESTAMP=`date +%s`;
            DATE=`date -d @$TIMESTAMP`;
            ACCOUNT=`bx target | grep Account: | cut -d' ' -f2-  | sed -e 's/^[ ][ ]*//g' | sed -e 's/[ ][ ]*$//g'`;
            USER=`bx target | grep User: | cut -d' ' -f2-  | sed 's/^[ ][ ]*//g' | sed -e 's/[ ][ ]*$//g'`;
            curl https://openwhisk.ng.bluemix.net/api/v1/web/cent%40us.ibm.com_ServiceManagement/default/BlueComputeAudit.json --data-urlencode "message={\"type\":\"bluecompute\",\"subtype\":\"audit\",\"space\":\"${BX_SPACE}\",\"org\":\"${BX_ORG}\",\"user\":\"${USER}\",\"account\":\"${ACCOUNT}\",\"date\":\"${DATE}\",\"audit_timestamp\":${TIMESTAMP},\"kube-cluster-name\":\"${KUBE_CLUSTER_NAME}\",\"api-endpoint\":\"${BX_API_ENDPOINT}\",\"registry\":\"${REGISTRY}\",\"registry-namespace\":\"${REGISTRY_NAMESPACE}\",\"creationTimestamp\":\"${CREATION_TIMESTAMP}\",\"component\":\"{{ .Chart.Name }}-{{ .Chart.Version }}\",\"comment\":\"${COMMENT}\",\"message\":\"${USER} has deployed {{ .Chart.Name }}-{{ .Chart.Version }} on $HOSTNAME\",\"IP address\":\"$IPADD\"}"
        imagePullPolicy: Always
        env:
        - name: KUBE_CLUSTER_NAME
          value: {{ .Values.global.bluemix.clusterName }}
        - name: BX_ORG
          value: {{ .Values.global.bluemix.target.org  }}
        - name: BX_SPACE
          value: {{ .Values.global.bluemix.target.space }}
        - name: BX_API_ENDPOINT
          value: {{ .Values.global.bluemix.target.endpoint }}
        - name: BLUEMIX_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-bluemix-api-key
              key: api-key
