{{ if and .Values.global.istio.enabled .Values.mysql.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "bluecompute.mysql.fullname" . }}
spec:
  hosts:
    - {{ template "bluecompute.mysql.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  http:
  - route:
    - destination:
        host: {{ template "bluecompute.mysql.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        #subset: v1
{{ end }}