---
# Source: bluecompute-ce/charts/couchdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: customer-couchdb-svc-couchdb
  labels:
    app: couchdb
    chart: couchdb-1.1.1
    release: bluecompute
    heritage: Helm
spec:
  ports:
    - port: 5985
      protocol: TCP
      targetPort: 5984
  type: ClusterIP
  selector:
    app: couchdb
    release: bluecompute
