---
# Source: bluecompute-ce/charts/mysql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-mysql
  labels:
    app: inventory-mysql
    chart: "mysql-0.15.0"
    release: "bluecompute"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app: inventory-mysql
  template:
    metadata:
      labels:
        app: inventory-mysql
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:latest"
        imagePullPolicy: "IfNotPresent"
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      # - name: do-something
      #   image: busybox
      #   command: ['do', 'something']

      containers:
      - name: inventory-mysql
        image: "mysql:5.7.14"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-mysql
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-mysql
              key: mysql-password
        - name: MYSQL_USER
          value: "dbuser"
        - name: MYSQL_DATABASE
          value: "inventorydb"
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        # - name: extras
        #   mountPath: /usr/share/extras
        #   readOnly: true

      volumes:
      - name: data
        emptyDir: {}
      # - name: extras
      #   emptyDir: {}
