apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: bluecompute-psp-users
subjects:
- kind: ServiceAccount
  name: default
  namespace: bluecompute
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: bluecompute-psp-user